name: Node.js CD

on:
  push:
    branches: [ deploy ]
  pull_request:
    branches: [ deploy ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install npm dependencies
      run: npm install
    - name: Run build task
      run: npm run build --if-present
    - name: Deploy to Server
      uses: appleboy/scp-action@master
      with:
       host: ${{ secrets.REMOTE_HOST }}
       username: ${{ secrets.REMOTE_USER }}
       port: ${{ secrets.REMOTE_PORT }}
       key: ${{ secrets.SSH_PRIVATE_KEY }}
       source: "build/*"
       rm: true
       target: "${{ secrets.REMOTE_TARGET }}"
